apiVersion: v1
kind: Service
metadata:
  labels:
    app: drupal-app
    app.kubernetes.io/component: drupal-app
    app.kubernetes.io/instance: drupal-app
    app.kubernetes.io/part-of: drupal-wxt
  name: drupal-app
spec:
  ports:
    - name: 8080-tcp
      port: 8080
    - name: 8443-tcp
      port: 8443
  selector:
    app: drupal-app
    deploymentconfig: drupal-app
