apiVersion: v1
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database_name'']}'
    template.openshift.io/expose-password: '{.data[''database_password'']}'
    template.openshift.io/expose-username: '{.data[''database_user'']}'
  name: drupal-db
type: Opaque
data:
  database_name: ZHJ1cGFs
  database_password: ZHJ1cGFs
  database_user: ZHJ1cGFs
