kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: drupal-cicd
  labels:
    app: drupal-cicd
    group: drupal
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: drupal-wxt
  source:
    path: overlays/non-prod/01-namespaces/argocd
    repoURL: https://github.com/pittar-sandbox/dotnet-contoso-gitops-admins.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    retry:
      limit: 5 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 3m # the maximum amount of time allowed for the backoff strategy